const enUS = {
  'welcome' : 'Welcome to the MMP App!',
  'create_word': 'Create a new word.',
  'view_all_words': "View all words.",
  'settings': "Settings",
  'exit': "Exit the program.",
  'error': "Error command entered",
  'new_word_name': "Enter a name for the new word: ",
  'file_error': "The note name entered was previously created, please try again.",
  'write_word': "Enter translation:",
  'save': 'save',
  'word_save': "Word successfully saved!",
  'number_word': "Enter the Word number",
  'delete_all': "Delete all notes",
  'delete_selected': "Selective deletion",
  'no_word': "No words yet!",
  'back_to_home': "Return to the main menu.",
  'enter_word_number': "Enter the Word number: ",
  "update": "Edit",
  "delete": "Delete",
  "back_to": "Back to",
  'previous_word': "Previous word:",
  'success_delete_all': "All files deleted successfully!",
  'select_file': "Select the directory file number and enter:",
};