const uzUZ = {
  'welcome' : 'MMP Appga Xush Kelibsiz!',
  'create_word': 'Yangi so\'z qo\'shish.',
  'view_all_words': "Barcha so'zlarni ko'rish.",
  'settings': "Sozlamalar",
  'exit': "Dasturdan chiqish.",
  'error': "Xato buyruq kiritildi",
  'new_word_name': "So'zni ingliz tilida kiriting: ",
  'file_error': "Kiritilgan note nomi oldin yaratilgan, Iltimos qayta urunib ko'ring.",
  'write_word': "Tarjimasini kiriting: ",
  'save': 'save',
  'word_save': "So'z muvaffaqiyatli saqlandi!",
  'number_word': "So'z raqamini kiriting",
  'delete_all': "Barcha so'zlarni o'chirish",
  'delete_selected': "Tanlab o'chirish",
  'no_word': "Hozircha so'zlar mavjud emas!",
  'back_to_home': "Bosh menuga qaytish.",
  'enter_word_number': "So'z raqamini kiriting: ",
  "update": "O'zgartirish",
  "delete": "O'chirish",
  "back_to": "Ortga qaytish",
  'previous_word': "Avvalgi so'z:",
  'success_delete_all': "Tanlangan so'zlar muvoffaqiyatli o'chirildi!",
  'select_file': "Yodlangan so'zlarni raqamini tanlab kiriting:",
  'edit_word' : "O'zgarishni kiriting: ",
  'sure' : "Ishonchingiz komilmi?",
  'yes' : "ha",
  'no' : "yo'q",
  "stop_to_delete" : "Amalni tugatish uchun 'save' so'zini kiriting",
  "write_description" : "So'zning tavsifini kiriting",
  "write_example" : "So'zga misol kiriting",
  "test" : "TEST",
  "missing_word": "So'zdan tushib qolgan harfni topish",
  "correct_answers": "To'g'ri javoblar soni",
  "percent" : "To'g'ri javoblar foizda",
  "update_lang" : "Tilni tanlang\n",
  "which_letter": "Qaysi harf kiritilishi kerak?",
};